### PR TITLE
Sentence structure

### PR DESCRIPTION
**Pull request by wurstbrot**
More important is to highlight the failure of security tests, e.g. SAST

### CODE REVIEW

**Comment by itscooper** [comment]
Thanks Timo! I’ll look at merging this into our working copy rather than beta. We are lacking a contributing.md and have a strange way or working on and releasing versions.

**Comment by wurstbrot** [comment]
Where do I find that working copy so I can add my other suggestions/PRs there?

**Comment by itscooper** [comment]
https://github.com/OWASP/samm/tree/master/Current%20Releases/head

**Comment by wurstbrot** [comment]
I am soo blind...

**Pull request merged**
