### PR TITLE
"Changing spelling + grammar +  markdown fix"

### PR DESCRIPTION
**Pull request by connorcarr**
This fixes minor spelling/grammar, but also fixes the table formatting issue on the GitHub page to ensure clarity.

I've consulted the HuGo markdown formatting at https://sourceforge.net/p/hugo-generator/wiki/markdown_syntax/#md_ex_tables and ensured the {{< table "table" >}} wasn't necessary for that, please do correct me if the table declaration was for something I'm missing, but I imagine it is a remnant of the old site.

### CODE REVIEW

**Comment by Pat-Duarte** [comment]
Thanks for catching the typos! The table is a Hugo shortcode, not an error in the markdown syntax.

**Comment by johnellingsworth** [comment]
@Pat-Duarte  Is this okay to be merged into master?

**Comment by Pat-Duarte** [comment]
No, we're not merging this! We need to create a new branch to fix the typos but, as I mentioned, we don't want the changes to the table. It's not an error in syntax. It's shortcodes.

**Comment by connorcarr** [comment]
Yep that's my fault, apologies I'll fix the pr

**Comment by connorcarr** [comment]
The requested edits have been made, thanks for your help clarifying!

**Pull request merged**
