### PR TITLE
update FAQ page on the website

### PR DESCRIPTION
**Pull request by SebaDele**
replaced the lorem ipsum introduction
update the existing questions to reflect the v2 release
added a section on how to contribute

### CODE REVIEW

**Comment by Pat-Duarte** [comment]
@SebaDele, shouldn't we add the contributing to GitHub markdown file to the current website?

**Comment by SebaDele** [comment]
> @SebaDele, shouldn't we add the contributing to GitHub markdown file to the current website?

I would keep the focus of the website on SAMM "consumers" and use the GitHub for contributions and project collaboration.
so the contribution page on github is on the correct location: no?

**Comment by SebaDele** [comment]
> I'd remove the "How to use SAMM?" H1
> Reasoning:
> 
> * Why the H1? The main title is part of the header.
> * If we want sections, we can wait until we have more, right?
>   In any case, "How to use SAMM?" is either "How to use SAMM" (not a question) or "How do I use SAMM?"

I will remove the H1 heading, indeed too early for sections

**Comment by SebaDele** [comment]
> I'd remove the "How to use SAMM?" H1
> Reasoning:
> 
> * Why the H1? The main title is part of the header.
> * If we want sections, we can wait until we have more, right?
>   In any case, "How to use SAMM?" is either "How to use SAMM" (not a question) or "How do I use SAMM?"

I have update this and made some other cosmetic changes.

**Pull request merged**
