### PR TITLE
Fixed all formulas and formating

### PR DESCRIPTION
**Pull request by practikl-OWASP**
Fixed all formulas and formating of "Roadmap" tab.

### CODE REVIEW

**Review by johanlindfors — APPROVED** [review]
Since it's kind of hard to do diff's on .xslx files I've downloaded the proposed file and it looks good to me. I also noticed the formulas was off in the roadmap sheed but they seems to have been fixed in this PR. Please approve asap!

**Comment by dkefer** [comment]
Hey @23bartman and @johnellingsworth,

I've looked over the file. Even if the bugs are meanwhile fixed in the new repository, **I propose to merge this PR**, e.g. for cases where this location is linked by various sources. 

Many thanks for your efforts @practikl-OWASP and @johanlindfors and sorry that this PR went unnoticed for so long :/

Best
Daniel

**Review by dkefer — APPROVED** [review]

**Comment by dkefer** [comment]
(changing assignee to @23bartman )

**Comment by practikl-OWASP** [comment]
You're welcome!

-------
*Patrick Leclerc*
*OWASP Quebec city <https://owasp.org/www-chapter-quebec-city/>*
-------

**Comment by SebaDele** [comment]
already fixed by another PR

**Pull request closed without merging**
